OPENPKGURI=http://files.kolab.org/server/release/kolab-server-2.2.0/sources/

include ../make-helper/kolab.mk

PACKAGE=perl-ssl
DOWNLOAD_VERSION=5.10.0
OPENPKG_RELEASE=20080101
VERSION=5.10.0
RELEASE=20080101_kolab1

SOURCE_URL=http://files.kolab.org/server/development-2.2/externals
SOURCE_0=Net-SSLeay-1.36.tar.gz

PATCHES=

EXTRA=kolab.patch

BUILD_OPTIONS=

include ../make-helper/package.mk
include ../make-helper/openpkg-patched.mk
include ../make-helper/fetch.mk
