OPENPKGURI=http://files.kolab.org/server/release/kolab-server-2.2.0/sources/

include ../make-helper/kolab.mk

PACKAGE=db
DOWNLOAD_VERSION=4.5.20.2
OPENPKG_RELEASE=20070628
VERSION=4.5.20.2
RELEASE=20070628_kolab1

SOURCE_URL=
SOURCE_0=

PATCHES=

EXTRA=kolab.patch

BUILD_OPTIONS=

include ../make-helper/package.mk
include ../make-helper/openpkg-patched.mk
include ../make-helper/fetch.mk
